### ISSUE TITLE
User defined operators - name not recognized

### ISSUE THREAD

**Issue by stephentetley** [flix/flix#2535]
At somepoint since 0.24.0, user defined operators have stopped working w.r.t namespaces.

Sample program:

~~~

def main(_args: Array[String]) : Int32 & Impure = 
    use Operator.{<&>};
    Console.printLine("Running...");
    (true <&> true) |> println;
    0

namespace Operator {

    pub def <&>(x: Bool, y: Bool): Bool = x and y

}

~~~

Output with current head:

~~~

-- Resolution Error -------------------------------------------------- ..\..\flix-doodle\temp\Operators.flix

>> Undefined name '<&>'.

4 |     (true <&> true) |> println;
              ^^^
              name not found




Compilation failed with 1 error(s).

Process finished with exit code 1

~~~

Output with 0.24.0:

~~~

Running...
true

~~~

**Comment by magnus-madsen** [comment]
There are very few PRs since 0.24.0 that would seem to touch that code. Could be https://github.com/flix/flix/pull/2513/files. @mlutze Do you want to take a look?

**Comment by magnus-madsen** [comment]
Confirmed works with 0.24.0 and broken in master.

**Comment by magnus-madsen** [comment]
Is suspect this line:

https://github.com/flix/flix/pull/2513/files#diff-ecb9df81b3be826080f39bf570a3a23e2a7587eb28d967085ac72d759be4ebdaR611

**Comment by stephentetley** [comment]
Thanks Magnus and Matthew!
